openapi: 3.0.1
info:
  title: Authentication Test Case
  description: Demonstrate various authentication methods supported by RapiDoc
servers:
  - url: https://reqres.in/api/
paths:
  /users/{userId}:
    get:
      description: Uses HTTP Basic Auth
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
            example: 3
          required: true
          description: Numeric ID of the user to get
      security:
      - http-basic: []

  /users:
    get:
      description: Uses API Key Auth
      security:
      - api_key1: []
components:
  securitySchemes:
    http-basic:
      type: http
      scheme: basic
    api_key1:
      type: apiKey
      name: Authorization
      in: header
