openapi: 3.0.2
info:
  version: '1.0'
  title: External refs (json-pointers)
  description: >
    Following OpenAPI spec demonstrate how to use external reference


    below is the main spec, but the schema used in the response is defined in a separate file named - schema.yaml
    
    ```yaml

    openapi: 3.0.0
    info:
      title:  Dynamic Form Params 
      version: 1.0.0
    paths:
      /user1:
        get:
          description: List User
          summary: List User
          responses:
            '200':
              description: The response
              content:
                application/json:
                  schema: 
                    $ref:'./schema.yaml#/components/schemas/user' <<< relative to html where rapidoc element is defined
    ```          
    
    schema.yaml

    ```yaml

    openapi: 3.0.2
    info:
      title: Partial spec for schema
      version: 1.0.0
    components:
      schemas:
        user:
          properties:
            id:
              type: integer
            name:
              type: string    
    ```          
    
 
paths:
  /external-refs:
    get:
      summary: External Refs
      description: Using external refs in spec
      responses:
        '200':
          description: >
            The response schema is defined in a separate file. If external refs are resolved properly then it should display the below schema

            ```json
              {
                id: integer
                name: string
              }
            ``` 
          content:
            application/json:
              schema: 
                $ref: '../specs/partial.yaml#/components/schemas/user'