openapi: 3.0.2
info:
  version: '1.0'
  title: External refs (json-pointers)
paths:
  /external-refs:
    get:
      summary: External Refs
      description: Using external refs in spec
      responses:
        $ref: ../specs/partial-responses.yaml
