openapi: 3.0.0
info:
  title: Request Parameters Test Cases
  description: Various request parameters types with defaults, examples and allowed values
  version: 1.0.0
paths:

  /request-body-data-as-json:
    post:
      summary: 2. Request body as JSON
      tags:
        - Request Parameters
      requestBody:
        description: Request body as **JSON**
        required: true
        content:
          application/json:
            schema:
              anyOf:
                - title: Option 1
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      age:
                        type: integer
                - title: Option 2
                  type: array
                  items:
                    type: object
                    properties:
                      location:
                        type: string
                      pin:
                        type: integer

